### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by JeroenVinke** [showdownjs/prettify-extension#4]
Hi, we are getting this warning:

```
DEPRECATION WARNING: prettify is an old extension that uses a deprecated loading method.Please inform the developer that the extension should be updated!
```

And it origins [here](https://github.com/showdownjs/showdown/blob/master/src/converter.js#L91). Can you please update this extension so it uses the new loader method? 

Thanks!

**Comment by tivie** [comment]
Should be fixed now

**Comment by JeroenVinke** [comment]
Thank you!
