### ISSUE TITLE
Needs include prettify as well?

### ISSUE THREAD

**Issue by leocaseiro** [showdownjs/prettify-extension#5]
Hi, thanks for this plugin. It seems working well. 
I have the string:

``` html
<a href="#">link</a>
```

That converts the follow html:

``` html
<pre class="prettyprint linenums">
    <code class="html language-html">&lt;a href="#"&gt;link&lt;/a&gt;</code>
</pre>
```

However, there's no syntax highlighter in here. Do I need to include any css?

PS: If I include the `run_prettify.js` it works. It supposed to be it?

``` html
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
```

Thanks

**Comment by obedm503** [comment]
same thing happening here
without the run_prettify,js, nothing in code blocks is highlighted

**Comment by tivie** [comment]
You need to include prettifyjs in your page for the code to be highlighted
